### ISSUE TITLE
Search icon should be a magnifying glass

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassx#11]
The current search icon shows up as a computer screen, and makes zero sense. This should be changed to a magnifying glass.

**Comment by TheZ3ro** [comment]
For me (in the develop branch) the icon is this:
![system-search](https://cloud.githubusercontent.com/assets/686894/19213759/56749b1e-8d74-11e6-8c3f-a41f8317b8dc.png)

**Comment by TheZ3ro** [comment]
For me (in the develop branch) the icon is this:
![system-search](https://cloud.githubusercontent.com/assets/686894/19213759/56749b1e-8d74-11e6-8c3f-a41f8317b8dc.png)

**Comment by droidmonkey** [comment]
Interesting, mine is:

![search_icon](https://cloud.githubusercontent.com/assets/2809491/19215439/e655a11e-8d6b-11e6-9b17-85903d845a32.png)

Probably a lookup issue, should package the icon with the app.

**Comment by droidmonkey** [comment]
This was an issue with my icon configuration on my system.
