### ISSUE TITLE
Auto-lock is currently broken when in edit password screen

### ISSUE THREAD

**Issue by t4777sd** [keepassxreboot/keepassx#13]
Currently auto-locking the database after X seconds does not work for the most common use-case. The reason is because when the database locks while a password entry is open a dialog will popup which prevents the actual locking.

To solve this there should only be a dialog box if there is an actual change to the database. And, in addition, there should be an option to auto-save the DB upon locking so that it can always lock correctly.

**Comment by droidmonkey** [comment]
The auto-locking of the database with the edit dialog open was fixed in 8a50ee8b.
