### ISSUE TITLE
Branch Strategy

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassx#24]
Opening up a discussion on the branching strategy. My though is to maintain a git-flow-lite structure.

- master -> always points to the last release published
- develop -> points to the next planned release, tested and reviewed code
- feature/[name] -> points to brand new feature in codebase, candidate for merge into develop (subject to rebase)

My thought is that brand new code should be vetted by the community, and also on several different platforms, prior to integration into the main baseline.

I plan to modify the CONTRIBUTE file to outline this strategy and also only accept PR's levied on the develop and feature branches.

**Comment by Manko10** [comment]
Agree. Additionally, there should always be an issue for each feature or bug fix in this tracker for documentation purposes. Pull requests don't necessarily need a separate issue because they are already documented.

**Comment by droidmonkey** [comment]
Issues/PRs can (and should) be referenced in the commit messages, but including it in the feature name won't hurt either.

**Comment by TheZ3ro** [comment]
I think it's a good flow, :+1:
I'm with @Manko10 about opening an issue/pull request for every new feature added (pull request will automatically do this)
We need also a template for Issue and Pull Request 
https://github.com/blog/2111-issue-and-pull-request-templates
