### ISSUE TITLE
KeePassX v2.0.2 on Ubuntu 16.04 - no KeepassHTTP settings

### ISSUE THREAD

**Issue by JoeArcher007** [keepassxreboot/keepassx#31]
I recently cloned the git repository, and ran through building the application on my computer. I can't seem to find the KeePassHTTP settings.

I don't think I made any errors in creating the application. 

Revision: b654fde9cd43202903c0e9e08b2043315335759b
KeePassX 2.0.2

If you require any more information, please let me know.

**Comment by droidmonkey** [comment]
You checked out the version of KeePassX prior to the HTTP implementation. Please use the develop or master branch.
