### ISSUE TITLE
The way currently the favicon downloading works, doesn't work with some websites.

### ISSUE THREAD

**Issue by magkopian** [keepassxreboot/keepassx#32]
Currently, for downloading the favicon of a website we are relying on Google by doing the following trick,

```c++
QString path = "http://www.google.com/s2/favicons?domain=" + url.host();
```

This though doesn't work with some websites, with [packagist.org](http://www.google.com/s2/favicons?domain=packagist.org) being such an example. For finding the favicon a typical web browser first checks the HTML code of the web page for one of the following tags,

```html
<link rel="shortcut icon" href="http://example.com/myicon.ico">
<link rel="icon" type="image/vnd.microsoft.icon" href="http://example.com/image.ico">
<link rel="icon" type="image/x-icon" href="http://example.com/image.ico">
<link rel="icon" href="http://example.com/image.ico">
<link rel="icon" type="image/gif"  href="http://example.com/image.gif">
<link rel="icon" type="image/png" href="http://example.com/image.png">
```

If neither of those are being found, then the web browser checks if the file `favicon.ico` exists on the root of the website. So, to do it properly we first need to download the HTML code, parse it in order to find one or more of those tags, try to fetch the favicon based on them and if it is unsuccessful try to fetch the `favicon.ico` file from the root of the website.

If you agree with this I can take a look to see if I can implement this, so we can make the download of the favicon more robust and we won't have to rely on Google for something like that, which might actually stop working in the future and break that functionality of the application.

#30

**Comment by TheZ3ro** [comment]
By me it's ok. :+1:

**Comment by stmllr** [comment]
keepassx is a tool you put some of your best secrets into. Users believe that it tries to provide the highest security as possible.

This might be undermined by putting libs + implementation to download + parse a web page into it. The favicon feature is nice, but not mandatory. Keep it simple + stupid.

**Comment by magkopian** [comment]
@stmllr The problem is that relying on a third party service for a feature of a standalone application like this, automatically takes the control away from the user. If in the future Google decides to change their URL structure or simply drop that feature, that will make the application to break and the user will not be able to do anything about it. Additionally, users who run an older version of the application and are not be able to update from some reason even when the problem is fixed from our part will be stuck with that issue.

Parsing the web page is not as hard as it sounds when you are looking for something specific, it can be done with just regular expressions, we aren't trying to parse every tag just locate a specific piece of information.

**Comment by droidmonkey** [comment]
This is a password manager, not a web scraper. This is also a "nice to have" feature, it might not work in all cases. The current implementation will stand.

**Comment by magkopian** [comment]
@droidmonkey In that case, then why just not try to fetch the `favicon.ico` from the root of the website and if it doesn't exist fallback to Google? From my experience as a web developer the majority of the websites keep a `favicon.ico` on their root as a fallback for older browsers that aren't able to parse the tags. Doing this only requires a couple of extra lines of code and should be enough to make the feature work with the majority of the websites and we stop relying as much to Google that way.

**Comment by TheZ3ro** [comment]
I think would be nice a setting to prevent the favicon feature because using Google can be a security issue (will track user request/metadata/IP/etc)

**Comment by magkopian** [comment]
@TheZ3ro Yes, I was thinking of that privacy issue as well, if we use though the method I proposed on my last comment, trying to fetch the `favicon.ico` file from the root of the website and only use Google as a fallback it's not that bad. It would be useful though to add a setting to disable the fallback to Google entirely for users who don't like being tracked by Google, and just make it so it will only try to fetch the favicon from the root folder of the website.

**Comment by droidmonkey** [comment]
@TheZ3ro the use of the icon grabbing code is by manual clicking a button, it does not automatically reach out and grab icons.

I do kinda like the idea of *first* finding the .ico, then moving to the google tool. Open a new issue that specifically requests that or create a PR with the code changes required.

**Comment by TheZ3ro** [comment]
@droidmonkey ok so it's fine by me

**Comment by magkopian** [comment]
@droidmonkey Ok, on it. I'll implement this and I'll send a pull request.
