### ISSUE TITLE
Translation from Transifex

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassx#35]
We need to make a new Transifex project for KeePassX Reboot, some new strings don't have translation right now.

**Comment by droidmonkey** [comment]
I created a new project and added the link to the readme. I don't see any easy way (yet) to back-fill already completed translations into transifex.

**Comment by TheZ3ro** [comment]
Don't tell me that we need to add all the translation manually on transifex

**Comment by droidmonkey** [comment]
OK I won't. ;-)

**Comment by droidmonkey** [comment]
I found out how to upload translations, so just need to spend some time uploading them all.

**Comment by TheZ3ro** [comment]
Nice news!

**Comment by droidmonkey** [comment]
All translations have been uploaded and marked as reviewed. I also linked the microsoft translation api service so "machine translations" should be possible for the easy strings.
