### ISSUE TITLE
Unlocked tray icon

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassx#37]
From: https://github.com/keepassx/keepassx/pull/123

> This PR brings back the feature from the old KeePassX release - database lock status indication via the system tray icon. Default application icon is used when all opened databases are unlocked, and special "locked" icon is used otherwise.
> 
> NOTE: The "locked" version of status icon was created only as a concept (I'm not a graphic designer what so ever). Also, I've not generated any PNG version of this icon

**Comment by TheZ3ro** [comment]
We can close this when the commit is merged to develop branch I think :wink:

**Comment by droidmonkey** [comment]
For some reason I can't get this to work on XFCE 4.12. All the code gets called properly. I think its because of the sole reliance on using the svgx instead of making separately sized pngs as well. I'm going to experiment a little more...

**Comment by TheZ3ro** [comment]
On some Desktop Environment svgz are not supported I think, se should generate the pngs

**Comment by samrocketman** [comment]
> We can close this when the commit is merged to develop branch I think :wink:

If you add `fixes #37` (or `closes #37`) in the commit message or pull request description, then GitHub will auto-close it post-merge.

**Comment by TheZ3ro** [comment]
> If you add fixes #37 (or closes #37) in the commit message or pull request description, then GitHub will auto-close it post-merge to the default branch.

Wow, nice to know

**Comment by samrocketman** [comment]
> Wow, nice to know

See https://help.github.com/articles/closing-issues-via-commit-messages/
