### ISSUE TITLE
Create a new icon to represent KeePassX-Reboot

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassx#41]
A new icon is needed to differentiate KeePassX from KeePassX-Reboot. Icon submissions are welcome, please post to this issue thread. Monochromatic / other styles are welcome for future theme-ing purposes.

**Comment by TheZ3ro** [comment]
Note: We also need to keep an eye on the icon's license 
https://github.com/keepassxreboot/keepassx/blob/develop/COPYING

**Comment by droidmonkey** [comment]
Discussion continued in Google Groups: https://groups.google.com/forum/#!topic/keepassx-reboot/tJhYaTt3rqc

**Comment by TheZ3ro** [comment]
Updated here https://github.com/keepassxreboot/keepassx/issues/61

We can close this now
