### ISSUE TITLE
Fix Travis-CI Build

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassx#6]
The current build breaks due to libmicrohttpd being a very old version on ubuntu 14.04 (Travis-CI version). Currently investigating work arounds to this on travis-fixes branch.

**Comment by timeraider4u** [comment]
maybe updating the .travis script by adding a newer package as a dependency might help: https://docs.travis-ci.com/user/installing-dependencies/

**Comment by droidmonkey** [comment]
Fixed in dee331d52d5df5b8b282eb8cfa7cbbc39ea77a62.
