### ISSUE TITLE
New Name and new Icon

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassx#61]
Since we are finally a separate fork, we have discuss the adoption of a new name and a new Icon.

The selected name and Icon are the following:

**KeePassXC - KeePass Cross-Platform Community edition**

![keepassxr](https://cloud.githubusercontent.com/assets/686894/19759878/3a5b0a70-9c2f-11e6-9382-0b618aabaf7b.png)

This is the last call, if you have ideas/opinion/changes speak out now.

Groups discussion https://groups.google.com/forum/#!topic/keepassx-reboot/tJhYaTt3rqc

**Comment by droidmonkey** [comment]
We beat this horse before but I thought of a new name:

KeePassXC - KeePass Cross Platform Community edition

It embodies the changes we implemented from KeePassX, ie take code, add features. and fix issues that the community recommends and desires.

**Comment by TheZ3ro** [comment]
By me is fine.
My only concern is that people wont understand the difference between KeePassX and KeePassXC (like what happen with KeePass and KeePassX) but who cares :smile:

**Comment by fourzerofour** [comment]
If the final name hasn't set in the stone, I'm proposing KeepPass or KeePasswd.

**Comment by droidmonkey** [comment]
@TheZ3ro are you going to start the PR for the new icon and name? If not I'll do this tonight. I am choosing KeePassXC

**Comment by TheZ3ro** [comment]
@droidmonkey I think that we need to merge the opened pull request before so we don't need to rebase after (in the name/icon PR)

Anyway if you start the PR for the name I will push the changes for the icon.

**Comment by droidmonkey** [comment]
Reminder, we also need a locked icon similar to what you did with the original keepassx icon.

**Comment by lebarondemerde** [comment]
Hello,

Please, when the final icon be decided, consider a black/white version for the Plasma/KDE system tray. 

Those icons, I think, are provided by the plasma theme, then would need to contact them.

Thank you!

**Comment by TheZ3ro** [comment]
@lebarondemerde i will do this ASAP.

**Comment by TheZ3ro** [comment]
@lebarondemerde i will do this ASAP.

EDIT: Added in this PR https://github.com/keepassxreboot/keepassx/pull/70

**Comment by dyskette** [comment]
Hello. Translation files are still keepassx, but I'm not sure if that should be an issue at all. So I just want to ask, is that going to change or is it going to stay that way?

I only notice when trying to make a package in rpm.

**Comment by phoerious** [comment]
What do you mean by that? We have our own translation files.

**Comment by dyskette** [comment]
Oh, sorry for the misunderstanding. I mean the name of the files, like `keepassx_XX.ts`.

**Comment by phoerious** [comment]
We also still have some defines that are called KEEPASSX_*. We may replace those in the incrementally, but it's no priority.
