### ISSUE TITLE
Feature Ideas from Long-Time Keepass user

### ISSUE THREAD

**Issue by t4777sd** [keepassxreboot/keepassx#7]
These are issues with KeePassX that do not exist in KeePass. It would be wonderful if these issues were fixed in KeePass Rebooted. Most of them are probably fairly simple to fix:

1) Auto-lock database is broken in KeePassX. There is the feature to lock database after X seconds, but it currently does not work. If you leave KeePassX open when inside of a password, then a dialog box will popup, which prevents the auto-close functionality. There is no reason for this dialog as long as there has been no changes to the DB which usually there is not.

2) Single window mode. KeePass has a nice feature where if you try to open two instances it will just open your existing open instance for you.

3) Search box is NOT visible by default. Searching passwords is probably the most common task in keepassx. Why does it require an extra click to toggle the search? That is likely one of the most used interface features and it is hidden!

4) When searching and a group is clicked on it currently disables the search. It should instead follow normal user interface standards for about every web app and application which is to filter by the selected group. There is already a cancel search button.

5) Configurable columns. There is no way to change the data shown in the password grid. I had view the last edited passwords and I had to download KeePass in order to view the last modified column and sort by it. It was impossible in Keepass

6) Standalone password generator. In KeePass you can generate passwords without creating a new password entry by going to the generator and generating one. This is very useful.

**Comment by Manko10** [comment]
7) Show unlock dialog when using the global autotype shortcut with a locked DB instead of showing an error message. This is a feature that has been requested a long time ago, but as with most things, there as been no progress at all.

**Comment by TheZ3ro** [comment]
8) Diceware-like passphrase generator from https://github.com/keepassx/keepassx/pull/181

9) Keyboard Injection instead of copy-paste

10) Database Merge

**Comment by droidmonkey** [comment]
Recommend you open an issue for each of the listed items, it is far easier to track and plan that way. Here is my personal prioritization order for the post:

1, 7, 9, 3, 4, 5, 6/8, 2, 10

**Comment by Manko10** [comment]
I've done that for my suggestion now.

**Comment by t4777sd** [comment]
I have created new issues for each of my suggestions, so this issue can be closed.

**Comment by TheZ3ro** [comment]
Done also for my suggestion. :+1:

**Comment by droidmonkey** [comment]
Thanks, closing this one
