### ISSUE TITLE
KeePass IOProtocolExt

### ISSUE THREAD

**Issue by lebarondemerde** [keepassxreboot/keepassx#71]
Since there have support for HTTP (WebDAV?), would be a good addition to also have support for SFTP.

There is a plug-in for KeePass called  [IOProtocolExt](http://keepass.info/plugins.html#ioprotocolext) what bring support to _SCP (Secure CoPy) protocol, SFTP (SSH File Transfer Protocol) and FTPS (FTP over SSH)_.

Support for [strong encryption](https://stribika.github.io/2015/01/04/secure-secure-shell.html) is always desirable too.

Please, consider _importing_ that plug-in.

Thank you.

**Comment by droidmonkey** [comment]
Not sure what you mean by this request. This version of KeePassX added support for the widely used browser plugin which incidentally uses http to communicate login information securely between KeePassX and the plugin.

What you describe above seems way out of scope for this project.

**Comment by lebarondemerde** [comment]
Ah, ok. I was with the impression the http support was related with database synchronization.

Sorry.

**Comment by droidmonkey** [comment]
!
